export const DEPARTMENTS = [
  {
    id: 1,
    name: "AE",
    fullname: "Automotive Engineering",
    icon: "car",
    color: "#ea4201",
  },
  {
    id: 2,
    name: "AES",
    fullname: "Applied Environmental Sciences",
    icon: "tree",
    color: "#98a900",
  },
  {
    id: 3,
    name: "AM",
    fullname: "Applied Maths",
    icon: "calculator",
    color: "#0e7bb7",
  },
  {
    id: 4,
    name: "AMEO",
    fullname: "Aeronautical Maintenance and Engineering Operations",
    icon: "user-astronaut",
    color: "#ccc",
  },
  {
    id: 5,
    name: "AMSN",
    fullname: "Advanced Materials Science and Nanotechnology",
    color: "#e4a188",
    icon: "atom",
  },
  {
    id: 6,
    name: "CHE",
    fullname: "Chemistry",
    color: "#eaf4be",
    icon: "vial",
  },
  {
    id: 7,
    name: "CS",
    fullname: "Cyber Security",
    color: "#25f2f7",
    icon: "key",
  },
  {
    id: 8,
    name: "DS",
    fullname: "Data Science ",
    color: "#e74941",
    icon: "database",
  },
  {
    id: 9,
    name: "EER",
    fullname: "Electrical Engineering and Renewable Energy",
    color: "#d39f52",
    icon: "lightning",
  },
  {
    id: 10,
    name: "EPE",
    fullname: "Engineering Physics and Electronics",
    color: "#3f141e",
    icon: "magnet",
  },
  {
    id: 11,
    name: "FST",
    fullname: "Food Science and Technology",
    color: "#378161",
    icon: "hamburger",
  },
  {
    id: 12,
    name: "ICT",
    fullname: "Information and Communication Technology",
    color: "#353f8c",
    icon: "laptop-code",
  },
  {
    id: 13,
    name: "MET",
    fullname: "Mechatronics Engineering Technology",
    color: "#6fabe4",
    icon: "tool",
  },
  {
    id: 14,
    name: "MST",
    fullname: "Medical Science and Technology",
    color: "#dbe177",
    icon: "plus",
  },
  {
    id: 15,
    name: "PMAB",
    fullname: "Pharmacological, Medical and Agronomical Biotechnology",
    color: "#9df2d8",
    icon: "pills",
  },
  {
    id: 16,
    name: "SSST",
    fullname: "Space Science and Satellite Technology",
    color: "#a98cd8",
    icon: "spaceship",
  },
];
